name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to create'
        required: true
        default: 'v0.0.0'

jobs:

  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
    # TODO: when 1.17 will be available
    # - name: Set up Go 1.x
    #   uses: actions/setup-go@v2
    #   with:
    #     go-version: ^1.17

    - name: Install Go
      run: |
          sudo rm -fr /opt/hostedtoolcache/go /usr/local/go /usr/bin/go /bin/go
          curl -o go.tar.gz -L \
            https://golang.org/dl/go1.17.linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf go.tar.gz
          sudo ln -s /usr/local/go/bin/* /usr/local/bin/
          go version

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build
      run: go build -v -gcflags=-G=3 ./...

    - name: Upload Coverage
      uses: codecov/codecov-action@v1
      continue-on-error: true
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: ./coverage.txt
        fail_ci_if_error: false

  release:
    if: github.event_name == 'workflow_dispatch'

    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Checkout with tags
        run: git fetch --prune --unshallow --tags

      - name: Create release
        run: |
          git log --format="%C(auto) %H %s" `git tag --sort=-committerdate | head -1`...HEAD > changelog.txt
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
          gh release create ${{ github.event.inputs.tag }} -F changelog.txt
